// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wheietzzsxokggwwesuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZWlldHp6c3hva2dnd3dlc3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDU0MDIsImV4cCI6MjA3MDgyMTQwMn0.pTJwyL2fO288C2_XVyiSOXfPml_IJnFTJg0bOl-TUKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});